os:
  - linux

language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

before_install:
  - jdk_switcher use oraclejdk8
  - java -version

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)
