os:
  - linux

language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_install:
  - jdk_switcher user oraclejdk8
  - java -version

script:
  - ./mvnw clean install
  - bash <(curl -s https://codecov.io/bash)