os:
  - linux

language: java
sudo: true

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

before_install:
  - jdk_switcher use oraclejdk8
  - java -version

before_script:
  - chmod a+x ./mvnw

script:
  - mvn clean install
